export const CONFIG = {
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN,
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  ENV: process.env.NODE_ENV,
  AUTH_TOKEN_KEY: process.env.NEXT_PUBLIC_AUTH_TOKEN_KEY,
  API_KEYS: {
    KAKAO: process.env.NEXT_PUBLIC_KAKAO_LOGIN_API_KEY,
  },
  // For: generate api
  SWAGGER_SCHEMA_PATH_NAME: process.env.SWAGER_SCHEMA_PATH_NAME,
  PAGINATION_KEYWORDS: process.env.PAGINATION_KEYWORDS,
  PAGINATION_KEY: process.env.PAGINATION_KEY,
} as const;
